CREATE TABLE cliente (
	id INT PRIMARY KEY AUTO_INCREMENT,
	id_plano INT,
	nome VARCHAR(50) NOT NULL,
	cpf VARCHAR(15) NOT NULL,
	email VARCHAR(100) NOT NULL,
	logradouro VARCHAR(50),
	numero VARCHAR(10),
	complemento VARCHAR(40),
	bairro VARCHAR(50),
	cep VARCHAR(10),
	cidade VARCHAR(50),
	estado VARCHAR(40)
) ENGINE=INNODB DEFAULT CHARSET=utf8;